import 'dart:ui';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
class AppColors {
  static const Color buttonColor = Colors.blue;
  static const Color primaryColor = Colors.black;
  static const Color secondaryColor = Colors.white;
  static Color secondaryButton = Colors.grey[300]!;
  static const Color selectedTextColor = Colors.white;
  static const Color unSelectedTextColor = Colors.black;
  static const Color dashboardAttendanceColor = Colors.green;
  static const Color dashboardLeavesColor = Colors.orange;
  static const Color dashboardLeavesStatusColor = Colors.purple;
  static const Color dashboardHolidayColor = Colors.blue;
  static const Color dashboardPayslipColor = Colors.teal;
  static const Color dashboardGridItemColor = Colors.teal;
  static const Color dashboardGridTextColor = Colors.black;
  static const Color dashboardReportsColor = Colors.redAccent;
  static const Color listHeadingsTextColor = Colors.green;
  static const Color leaveScreenTextColor = Colors.black45;
  static const Color listDescriptionTextColor = Colors.black87;
  static const Color successGreen = Color(0xff51f21f);
  static const Color successOrange = Color(0xfff27e1f);
  static const Color presenceClr = Colors.green;
  static const Color absenceClr = Colors.red;
  static const Color leavesClr = Colors.orangeAccent;
  static const Color lateClr = Colors.blue;
  static const Color leavesOverviewContClr = Colors.blue;
  static const Color leavesOverviewIconClr = Colors.blue;
  static  Color warningClr = Colors.brown[600]!;
  static const Color tagOfficeText = Colors.blue;
  static const Color tagOfficeBg = Color(0xFFD0E8FF);
  static const Color tagSelfieText = Colors.orange;
  static const Color tagSelfieBg = Color(0xFFFFE0B2);
  static const Color calendarBorder = Color(0xFFDADADA);
  static const Color calendarWeekday = Colors.blue;
  static const Color calendarWeekend = Colors.red;
  static const Color tagBorderClr = Colors.blue;
  static const Color publicClr = Color(0xFF4CAF50);
  static const Color optionalClr = Color(0xFFFFC107);
  static const Color halfDayClr = Color(0xFFFFC107);
  static const Color avgHrsClr = Color(0xFF2196F3);
  static const Color companyClr = Color(0xFF2196F3);

  static const Color progressTrackColor = Color(0xFFB3E5FC);
  static const Color progressColor = Colors.blue;
  static const Color greyBorder = Color(0xFFE0E0E0);
  static const Color approved = Colors.green;
  static const Color rejected = Colors.red;
  static  Color pending = Colors.yellow.shade600;
  static const netPayBackground = Color(0xFFD0F0C0);
  static const netPayAccent = Colors.green;
  //payslip screen
  static const Color white = Colors.white;
  static const Color black = Colors.black;
  static const Color grey = Colors.grey;
  static const Color grey100 = Color(0xFFF5F5F5);
  static const Color grey200 = Color(0xFFEEEEEE);
  static const Color grey300 = Color(0xFFE0E0E0);
  static const Color primaryBlue = Color(0xFF2196F3);
  static const Color blue50 = Color(0xFFE3F2FD);
  static const Color greenLight = Color(0xFFC8E6C9);
  static const payslipTitle = PdfColors.blue;
  static const payslipSubtitle = PdfColors.green;
  static const payslipLightGreen = PdfColors.lightGreen100;
  static const payslipDivider = PdfColors.grey300;
  static const payslipSectionBg = PdfColors.grey200;
  static const payslipHighlight = PdfColors.lightBlue100;
  static const payslipNetPayBg = PdfColors.green100;
  static const generatedTextColor = Colors.green;
  static const downloadTextColor = Colors.blue;
  // profile screen
  static const Color textGrey = Color(0xFF888888);
  static const Color whiteColor = Color(0xFFFFFFFF);
  static const Color gradientBlue = CupertinoColors.activeBlue;
  static const Color gradientGreen = Colors.green;


}
