// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRpzVaTgG-W6w5vToXdfoSx2tUW9ABWZs',
    appId: '1:427976472772:android:0f8ea6fb9ea3a74a04b191',
    messagingSenderId: '427976472772',
    projectId: 'ziya-attend-2c26c',
    storageBucket: 'ziya-attend-2c26c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3jHcnmQOz-ffSiMCymezjg62qKMXuxFA',
    appId: '1:427976472772:ios:efcf97950258bc3604b191',
    messagingSenderId: '427976472772',
    projectId: 'ziya-attend-2c26c',
    storageBucket: 'ziya-attend-2c26c.firebasestorage.app',
    iosBundleId: 'com.example.ziyaAttendanceUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJKU-WfGfv81uZ_hoqkKvbZHe9YfCe7M',
    appId: '1:427976472772:web:6caf32d1c6ff4df604b191',
    messagingSenderId: '427976472772',
    projectId: 'ziya-attend-2c26c',
    authDomain: 'ziya-attend-2c26c.firebaseapp.com',
    storageBucket: 'ziya-attend-2c26c.firebasestorage.app',
    measurementId: 'G-T4WW2PTPE7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3jHcnmQOz-ffSiMCymezjg62qKMXuxFA',
    appId: '1:427976472772:ios:efcf97950258bc3604b191',
    messagingSenderId: '427976472772',
    projectId: 'ziya-attend-2c26c',
    storageBucket: 'ziya-attend-2c26c.firebasestorage.app',
    iosBundleId: 'com.example.ziyaAttendanceUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTJKU-WfGfv81uZ_hoqkKvbZHe9YfCe7M',
    appId: '1:427976472772:web:85c552b46f20b7a504b191',
    messagingSenderId: '427976472772',
    projectId: 'ziya-attend-2c26c',
    authDomain: 'ziya-attend-2c26c.firebaseapp.com',
    storageBucket: 'ziya-attend-2c26c.firebasestorage.app',
    measurementId: 'G-G40XKHZXMW',
  );

}